In [13]:
import pandas
import numpy

In [14]:
dateDF = pandas.read_csv('https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/refs/heads/main/day34-handling-date-and-time/orders.csv')
timeDF = pandas.read_csv('https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/refs/heads/main/day34-handling-date-and-time/messages.csv')

In [15]:
dateDF.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [16]:
timeDF.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [18]:
dateDF['date'] = pandas.to_datetime(dateDF['date'])

In [23]:
dateDF['date_year'] = dateDF['date'].dt.year
dateDF['date_month'] = dateDF['date'].dt.month
dateDF['date_month_name'] = dateDF['date'].dt.month_name()
dateDF['date_day'] = dateDF['date'].dt.day
dateDF['date_day_name'] = dateDF['date'].dt.day_name()

In [24]:
dateDF.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_day_name
0,2019-12-10,5628,25,3,2019,12,December,10,Tuesday
1,2018-08-15,3646,14,157,2018,8,August,15,Wednesday
2,2018-10-23,1859,25,1,2018,10,October,23,Tuesday
3,2019-08-17,7292,25,1,2019,8,August,17,Saturday
4,2019-01-06,4344,25,3,2019,1,January,6,Sunday

In [26]:
timeDF['date'] = pandas.to_datetime(timeDF['date'])
timeDF['date_year'] = timeDF['date'].dt.year
timeDF['date_month'] = timeDF['date'].dt.month
timeDF['date_month_name'] = timeDF['date'].dt.month_name()

In [27]:
timeDF['date_day'] = timeDF['date'].dt.day
timeDF['date_day_name'] = timeDF['date'].dt.day_name()

In [28]:
timeDF['date_hour'] = timeDF['date'].dt.hour
timeDF['date_minute'] = timeDF['date'].dt.minute
timeDF['date_second'] = timeDF['date'].dt.second

In [29]:
timeDF.head()

,date,msg,date_year,date_month,date_month_name,date_day,date_day_name,date_hour,date_minute,date_second
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,2013,12,December,15,Sunday,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,2014,4,April,29,Tuesday,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,2012,12,December,30,Sunday,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,2014,11,November,28,Friday,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,2013,10,October,26,Saturday,23,11,0