# Column Transformer in Machine Learning using skLearn

In [10]:
import pandas

df= pandas.read_csv("https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/refs/heads/main/day28-column-transformer/covid_toy.csv")

df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [11]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [12]:
df.isnull().sum() #List all the NULL values in the Columns

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

## Column Transformer Code

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder , StandardScaler , OrdinalEncoder

ct = ColumnTransformer(
    transformers=[
        ('Gender' , OneHotEncoder(sparse_output=False) , ['gender']),
        ('Output' , OrdinalEncoder(categories=[['No' , 'Yes']]) ,['has_covid']),
        ('Cough' ,OrdinalEncoder(categories=[['Mild' , 'Strong']]) ,['cough'])
    ],
    remainder='passthrough'
)

df_transformedData = ct.fit_transform(df)

df = pandas.DataFrame(df_transformedData)

df.head()

     0    1    2    3   4      5        6
0  0.0  1.0  0.0  0.0  60  103.0  Kolkata
1  0.0  1.0  1.0  0.0  27  100.0    Delhi
2  0.0  1.0  0.0  0.0  42  101.0    Delhi
3  1.0  0.0  0.0  0.0  31   98.0  Kolkata
4  1.0  0.0  0.0  0.0  65  101.0   Mumbai